<a href="https://colab.research.google.com/github/akukudala/Akshitha_690/blob/main/Assignment05/Assignment_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment 05
* Intro to NumPy and exercises on NumPy
* Date: 3/5/2022

## What is the use of NumPy library?
* NumPy helps in number processing in Python. 
* NumPy uses primitive numeric types (floats, ints) which makes storing and computation efficient.


In [ ]:
import numpy as np

In [ ]:
n = 3


In [ ]:
2 ** n


8

In [ ]:
np.int8


numpy.int8

Numpy is array processing library

In [ ]:
import sys
import numpy as np

In [ ]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [ ]:
a = np.array([1, 2, 3, 4])


In [ ]:
b = np.array([0, .5, 1, 1.5, 2])

In [ ]:
a[0], a[1]

(1, 2)

In [ ]:
a[0:]

array([1, 2, 3, 4])

In [ ]:
a[1:3]

array([2, 3])

In [ ]:
a[1:-1]

array([2, 3])

In [ ]:
a[::2]

array([1, 3])

In [ ]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [ ]:
b[[0, 2, -1]]

array([0., 1., 2.])

Array Types

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
a.dtype


dtype('int64')

In [ ]:
b.dtype

dtype('float64')

In [ ]:
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [ ]:
np.array([1, 2, 3, 4], dtype=np.int8)


array([1, 2, 3, 4], dtype=int8)

In [ ]:
c = np.array(['a', 'b', 'c'])

In [ ]:
c.dtype

dtype('<U1')

In [ ]:
d = np.array([{'a': 1}, sys])

In [ ]:
d.dtype

dtype('O')

Dimensions and shapes

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [ ]:
A.shape

(2, 3)

In [ ]:
A.ndim

2

In [ ]:
A.size

6

In [ ]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [ ]:
B.shape

(2, 2, 3)

In [ ]:
B.ndim

3

In [ ]:
B.size

12

In [ ]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  import sys


* Indexing and Slicing of Matrices

In [ ]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [ ]:
A[1]

array([4, 5, 6])

In [ ]:
A[1][0]

4

In [ ]:
A[1, 0]

4

In [ ]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [44]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [45]:
A[:2, 2:]

array([[3],
       [6]])

In [46]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
A[1] = np.array([10, 10, 10])

In [49]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

## Summary statistics

In [50]:
a = np.array([1, 2, 3, 4])


In [51]:
a.sum()

10

In [52]:
a.mean()

2.5

In [53]:
a.std()

1.118033988749895

In [54]:
a.var()

1.25

In [55]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [56]:
A.sum()

45

In [57]:
A.mean()

5.0

In [58]:
A.std()

2.581988897471611

In [59]:
A.sum(axis=0)

array([12, 15, 18])

In [60]:
A.sum(axis=1)

array([ 6, 15, 24])

In [61]:
A.mean(axis=0)

array([4., 5., 6.])

In [62]:
A.mean(axis=1)

array([2., 5., 8.])

In [63]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [64]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

## Broadcasting and Vectorized operations

In [65]:
a = np.arange(4)

In [66]:
a

array([0, 1, 2, 3])

In [67]:
a + 10

array([10, 11, 12, 13])

In [68]:
a*10

array([ 0, 10, 20, 30])

In [69]:
a += 100

In [70]:
l = [0, 1, 2, 3]

In [71]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [72]:
a = np.arange(4)

In [73]:
b = np.array([10, 10, 10, 10])

In [74]:
a+b

array([10, 11, 12, 13])

In [75]:
a*b

array([ 0, 10, 20, 30])

## Boolean arrays

In [76]:
a = np.arange(4)


In [77]:
a[0], a[-1]

(0, 3)

In [78]:
a[[0, -1]]

array([0, 3])

In [80]:
a[[True, False, False, True]]

array([0, 3])

In [81]:
a >= 2

array([False, False,  True,  True])

In [82]:
a[a >= 2]

array([2, 3])

In [83]:
a.mean()

1.5

In [84]:
a[a > a.mean()]

array([2, 3])

In [85]:
a[~(a > a.mean())]

array([0, 1])

In [86]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [87]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [88]:
A = np.random.randint(100, size=(3, 3))

In [89]:
A

array([[79, 66, 77],
       [83, 16, 35],
       [74, 62, 62]])

In [90]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([79, 77, 16, 74, 62])

In [91]:
A > 30

array([[ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True]])

In [92]:
A[A > 30]

array([79, 66, 77, 83, 35, 74, 62, 62])

## Linear Algebra

In [93]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [94]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [95]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [96]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [97]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [98]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

## Size of objects in Memory

In [99]:
sys.getsizeof(1)

28

In [100]:
sys.getsizeof(10**100)

72

In [101]:
np.dtype(int).itemsize

8

In [102]:
np.dtype(np.int8).itemsize

1

In [103]:
np.dtype(float).itemsize

8

##  Lists are even larger

In [104]:
sys.getsizeof([1])


80

In [105]:
np.array([1]).nbytes


8

In [106]:
l = list(range(100000))


In [107]:
a = np.arange(100000)


In [108]:
%time np.sum(a ** 2)


CPU times: user 947 µs, sys: 0 ns, total: 947 µs
Wall time: 957 µs


333328333350000

In [109]:
%time sum([x ** 2 for x in l])


CPU times: user 40.9 ms, sys: 2.36 ms, total: 43.3 ms
Wall time: 48.1 ms


333328333350000

## Useful Numpy functions


In [110]:
np.random.random(size=2)



array([0.80500815, 0.46041875])

In [111]:
np.random.normal(size=2)


array([ 0.02988625, -0.90483824])

In [112]:
np.random.rand(2, 4)


array([[0.22612574, 0.84906968, 0.29987515, 0.63556547],
       [0.58017817, 0.49004187, 0.65324886, 0.26996655]])

In [113]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
np.arange(5, 10)


array([5, 6, 7, 8, 9])

In [115]:
np.arange(0, 1, .1)


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [116]:
np.arange(10).reshape(2, 5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [117]:
np.arange(10).reshape(5, 2)


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [118]:
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [119]:
np.linspace(0, 1, 20)


array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [120]:
np.linspace(0, 1, 20, False)


array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [121]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [122]:
np.zeros((3, 3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [124]:
np.zeros((3, 3), dtype=np.int8)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [125]:
np.ones(5)


array([1., 1., 1., 1., 1.])

In [126]:
np.ones((3, 3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [127]:
np.empty(5)


array([1., 1., 1., 1., 1.])

In [128]:
np.empty((2, 2))


array([[0.25, 0.5 ],
       [0.75, 1.  ]])

## identity and eye


In [129]:
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [130]:
np.eye(3, 3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [131]:
np.eye(8, 4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [132]:
np.eye(8, 4, k=1)


array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [133]:
np.eye(8, 4, k=-3)


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [134]:
"Hello World"[6]


'W'